"""Created username column & changed text to x-tweets in the tweets table

Revision ID: a1ba976ba58d
Revises: a3513d1269c5
Create Date: 2024-12-30 10:21:50.268294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ba976ba58d'
down_revision: Union[str, None] = 'a3513d1269c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('username', sa.String(), nullable=False))
    op.add_column('tweets', sa.Column('x_tweets', sa.String(), nullable=False))
    op.drop_column('tweets', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tweets', 'x_tweets')
    op.drop_column('tweets', 'username')
    # ### end Alembic commands ###
